#ifndef FILE_PLAYER_INPUT_HPP
#define FILE_PLAYER_INPUT_HPP

enum PlayerInput {
    // Player 1
    PLAYER1_UP,
    PLAYER1_LEFT,
    PLAYER1_RIGHT,
    PLAYER1_DOWN,
    PLAYER1_SHOOT,
    PLAYER1_GRAB,

    // Player 2
    PLAYER2_UP,
    PLAYER2_LEFT,
    PLAYER2_RIGHT,
    PLAYER2_DOWN,
    PLAYER2_SHOOT,
    PLAYER2_GRAB,

    // Player 3
    PLAYER3_UP,
    PLAYER3_LEFT,
    PLAYER3_RIGHT,
    PLAYER3_DOWN,
    PLAYER3_SHOOT,
    PLAYER3_GRAB,

    // Player 4
    PLAYER4_UP,
    PLAYER4_LEFT,
    PLAYER4_RIGHT,
    PLAYER4_DOWN,
    PLAYER4_SHOOT,
    PLAYER4_GRAB
};

#endif 