#ifndef FILE_PLAYER_INPUT_HPP
#define FILE_PLAYER_INPUT_HPP

enum PlayerInput {
    X_AXIS,
    Y_AXIS,
    SHOOT,
    GRAB,
    MOUSE_LEFT,
    MOUSE_RIGHT,
    SPEED_UP,
    SPEED_DOWN,
    SPEED_RESET,
    PAUSE,

    // Cheats
    SKIP_LEVEL,
    INFINITE_HEALTH,
    RANDOM_WEAPON,
    LASER_WEAPON,
    KILL_EVERYONE_EXCEPT_YOURSELF,
};

 #endif // FILE_PLAYER_INPUT_HPP